export const UserRole = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MERCHANT: 'MERCHANT',
  AGENT: 'AGENT',
} as const;

export const MerchantStatus = {
  NONE: 'NONE',
  ACTIVE: 'ACTIVE',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export const AuditAction = {
  SIGNUP: 'SIGNUP',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  MERCHANT_APPROVED: 'MERCHANT_APPROVED',
  MERCHANT_REJECTED: 'MERCHANT_REJECTED',
  USER_CREATED: 'USER_CREATED',
  USER_DELETED: 'USER_DELETED',
  LOGOUT: 'LOGOUT',
} as const;
